controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    number += 1
    mySprite.setPosition(list[number][0], list[number][1])
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    number = 0
    mySprite.setPosition(list[number][0], list[number][1])
})
let number = 0
let list: number[][] = []
let mySprite: Sprite = null
scene.setBackgroundColor(1)
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
list = [
[10, 10],
[80, 10],
[150, 10],
[10, 60],
[80, 60],
[150, 60],
[10, 110],
[80, 110],
[150, 110]
]
number = 0
mySprite.setPosition(list[number][0], list[number][1])
